### ISSUE TITLE
Issue with RuneLite's 'Always on top' setting

### ISSUE THREAD

**Issue by nasifra** [Psicoses/ChatFilterUpdater#2]
I installed the plugin and my client froze, not responding when I clicked it, even after restarting - I couldn't move the window. Looking at the processes in Task Manager I could see it was throwing up a pop-up for the plugin. I have RuneLite's *Always on top* setting enabled, so I suspect it's due to that.

I was able to maximise the warning pop-up in the back ground (via the process in Task Manager) so I can click on the OK/Cancel buttons, but this is very user-unfriendly.

Other pop-ups, such as those shown when using the **Inventory Setups** plugins work fine with *Always on top* enabled.

**Comment by Psicoses** [comment]
The warning should now show above Runelite in the next update. 630be04
